### ISSUE TITLE
We should have a 'develop' branch for active development by the community.

### ISSUE THREAD

**Issue by CaseyZS** [gcentral/top-level-launcher#3]

**Comment by chrisb2244** [comment]
To help someone who didn't join the mob session understand - is the suggestion here to make it possible for anyone to push to a develop branch, or to split development from specific packaging/build steps more forcefully than just with tags? (Or to build two types, in a 'nightly' vs stable type arrangement?)

(i.e. why is developing in forked repos and opening PRs against main not the preferred choice?)

**Comment by CaseyZS** [comment]
I was thinking in more of a gitflow paradigm where 'main' is reserved for updates/merges that are available for release vs 'develop' can have new features merged in that aren't yet built into a VIP.

**Comment by JayKayAce** [comment]
I have updated the develop branch with the latest changes on main.
