### ISSUE TITLE
Consider using the Shift functionality of QuickDrop to define vs execute the top level VI

### ISSUE THREAD

**Issue by CaseyZS** [gcentral/top-level-launcher#4]
We could combine the ability to define the top level VI and then execute it within a single QD plugin (rather than two).

I would suggest using 'shift' to define the top level VI because it happens less often. The regular non-shift shortcut would then be used to execute the VI.

**Comment by crossrulz** [comment]
Another option would be to use a text entry to set or run. This option would help with issue #5 as well.

**Comment by crossrulz** [comment]
I started implementing this capability.

**Comment by GIdeaExchange** [comment]
Closed by #9
