### ISSUE TITLE
Create List of Contributors

### ISSUE THREAD

**Issue by JayKayAce** [gcentral/top-level-launcher#8]
We should have a list of contributors so that every developer who contributes to the project can be mentioned accordingly when we do a new release. 

There must somehow be a way to connect this to the release process on Github so it is possible to see the contributors from the front page of the repository.

**Comment by GIdeaExchange** [comment]
Pending VIPM release and list of contributors created.

**Comment by JayKayAce** [comment]
Finished as part of the release v1.0
